### ISSUE TITLE
missing source code files named "EditorFunctions.h" and "EditorFunctions.cpp"

### ISSUE THREAD

**Issue by JianqiangDing** [KaiWenHsiao/Multi-view-Wire-Art#1]
Dear Kevin,

I've just noticed impressive results of this project recently, and there is a problem when I was trying to compile the source code to do some tests on my own.

did I miss something? it seems that you had forgotten to public two files named "EditorFuncitons.h" and "EditorFuncitons.cpp"

if possible, could you please upload these two files?

**Comment by KaiWenHsiao** [comment]
This program can be compiled without "EditorFunctions" and "EditorManager", so please directly remove the files ("EditorManager.h" and "EditorManager.cpp"), thank you !

**Comment by JianqiangDing** [comment]
thank you, it works :)

**Comment by fanqieo** [comment]
> 

你好，能帮我运行下程序吗？我有的图片放进去没办法生成出来，有的图片可以，我愿意给一定的费用？
